// ============================================================
// MAIN APP CONTROLLER - Assistive Joystick
// ============================================================

import { SerialManager } from './serial.js';
import { authModule } from './auth.js';

// ============================================================
// ARDUINO SKETCH TEMPLATE
// ============================================================
const SKETCH_TEMPLATE = `/*
  =============================================================================
  ASSISTIVE JOYSTICK — Tremor-Compensated Mouse Controller
  =============================================================================
  Board:    Arduino Leonardo (must be Leonardo for HID Mouse support)
  Joystick: 2-axis analog -> A0 (X), A1 (Y), button -> D3
  Safety:   D2 must be jumpered to GND to enable mouse output

  Generated by Assistive Joystick Web App
  =============================================================================
*/

#include <Mouse.h>

// PIN ASSIGNMENTS
const int PIN_X      = A0;
const int PIN_Y      = A1;
const int PIN_BUTTON = 3;
const int PIN_SAFETY = 2;

// PROFILE PARAMETERS
struct Profile {
  const char* name;
  float minCutoff;
  float beta;
  int   deadzone;
};

Profile PROFILES[] = {
  { "1 Steady",   5.00, 0.020,  8  },
  { "2 Mild",     2.00, 0.015, 12  },
  { "3 Moderate", 1.00, 0.010, 16  },
  { "4 Heavy",    0.50, 0.007, 20  },
  { "5 Severe",   0.25, 0.005, 26  },
};
const int NUM_PROFILES = sizeof(PROFILES) / sizeof(PROFILES[0]);
int currentProfile = %%PROFILE%%;

float cursorSpeed = %%SPEED%%;

// CALIBRATION
int centerX = 512, centerY = 512;
int rangeX  = 512, rangeY  = 512;

// AUTO-RECENTER
const unsigned long AUTO_RECENTER_MS = 2000;
const int STILL_THRESHOLD = 5;
float idleAvgX = 512.0, idleAvgY = 512.0;
const float IDLE_ALPHA = 0.05;
unsigned long stillSinceMs = 0;
bool isStill = false;

// SAMPLING
const float SAMPLE_RATE_HZ = 100.0;
const unsigned long SAMPLE_INTERVAL_MS = 1000.0 / SAMPLE_RATE_HZ;

// MEDIAN FILTER
float medianBufX[3] = {0,0,0};
float medianBufY[3] = {0,0,0};
int medianIdx = 0;

// ONE EURO FILTER
struct OneEuro { float xPrev, dxPrev, yPrev; bool initialized; };
OneEuro oneEuroX = {0,0,0,false};
OneEuro oneEuroY = {0,0,0,false};
const float DCUTOFF = 1.0;

// SUB-PIXEL
float cursorAccumX = 0.0, cursorAccumY = 0.0;

// STATE
unsigned long lastSampleMs = 0;
bool prevButton = false;

%%EXTRA_PINS%%

void setup() {
  pinMode(PIN_SAFETY, INPUT_PULLUP);
  pinMode(PIN_BUTTON, INPUT_PULLUP);
  %%EXTRA_SETUP%%
  Serial.begin(115200);
  delay(500);
  Serial.println(F("=== Calibrating — DO NOT TOUCH the joystick ==="));
  calibrateCenter(1500);
  Mouse.begin();
  Serial.println(F("=== Assistive Joystick Ready ==="));
  printSettings();
}

void loop() {
  handleSerial();
  unsigned long now = millis();
  if (now - lastSampleMs < SAMPLE_INTERVAL_MS) return;
  float dt = (now - lastSampleMs) / 1000.0;
  lastSampleMs = now;

  int rawX = analogRead(PIN_X);
  int rawY = analogRead(PIN_Y);

  // Auto-recenter
  idleAvgX = idleAvgX * (1.0 - IDLE_ALPHA) + rawX * IDLE_ALPHA;
  idleAvgY = idleAvgY * (1.0 - IDLE_ALPHA) + rawY * IDLE_ALPHA;
  bool stickStill = (abs(rawX - (int)idleAvgX) < STILL_THRESHOLD) &&
                    (abs(rawY - (int)idleAvgY) < STILL_THRESHOLD);
  if (stickStill) {
    if (!isStill) { isStill = true; stillSinceMs = now; }
    else if (now - stillSinceMs >= AUTO_RECENTER_MS) {
      centerX = (int)idleAvgX; centerY = (int)idleAvgY;
      oneEuroX.initialized = false; oneEuroY.initialized = false;
      cursorAccumX = 0; cursorAccumY = 0; stillSinceMs = now;
    }
  } else { isStill = false; }

  float normX = normalize(rawX, centerX, rangeX);
  float normY = normalize(rawY, centerY, rangeY);

  // Median filter
  medianBufX[medianIdx] = normX;
  medianBufY[medianIdx] = normY;
  medianIdx = (medianIdx + 1) % 3;
  float medX = median3(medianBufX[0], medianBufX[1], medianBufX[2]);
  float medY = median3(medianBufY[0], medianBufY[1], medianBufY[2]);

  // One Euro Filter
  Profile p = PROFILES[currentProfile];
  float filtX = oneEuroFilter(oneEuroX, medX, dt, p.minCutoff, p.beta);
  float filtY = oneEuroFilter(oneEuroY, medY, dt, p.minCutoff, p.beta);

  // Deadzone
  filtX = applyDeadzone(filtX, p.deadzone);
  filtY = applyDeadzone(filtY, p.deadzone);

  // HID Mouse
  bool mouseEnabled = (digitalRead(PIN_SAFETY) == LOW);
  if (mouseEnabled) {
    cursorAccumX += (filtX / 100.0) * cursorSpeed;
    cursorAccumY += (filtY / 100.0) * cursorSpeed;
    int dx = (int)cursorAccumX; int dy = (int)cursorAccumY;
    cursorAccumX -= dx; cursorAccumY -= dy;
    if (dx != 0 || dy != 0) Mouse.move(dx, dy, 0);

    bool buttonNow = (digitalRead(PIN_BUTTON) == LOW);
    if (buttonNow && !prevButton)  Mouse.press(%%BUTTON_ACTION%%);
    if (!buttonNow && prevButton)  Mouse.release(%%BUTTON_ACTION%%);
    prevButton = buttonNow;
    %%EXTRA_BUTTON_LOGIC%%
  } else {
    if (prevButton) { Mouse.release(%%BUTTON_ACTION%%); prevButton = false; }
    cursorAccumX = 0; cursorAccumY = 0;
  }

  // Telemetry
  Serial.print((int)filtX); Serial.print(',');
  Serial.print((int)filtY); Serial.print(',');
  Serial.println(mouseEnabled ? 1 : 0);
}

void handleSerial() {
  while (Serial.available()) {
    char c = Serial.read();
    if (c >= 'A' && c <= 'Z') c += 32;
    if (c >= '1' && c <= '5') {
      currentProfile = c - '1';
      Serial.print(F(">> Profile: "));
      Serial.println(PROFILES[currentProfile].name);
      oneEuroX.initialized = false; oneEuroY.initialized = false;
      printSettings();
    }
    else if (c == '0') { Serial.println(F(">> Calibrating center...")); calibrateCenter(1500); printSettings(); }
    else if (c == 'r') { Serial.println(F(">> Swirl stick...")); calibrateRange(3000); printSettings(); }
    else if (c == '+') { PROFILES[currentProfile].minCutoff = fmaxf(PROFILES[currentProfile].minCutoff - 0.25, 0.1); oneEuroX.initialized = false; oneEuroY.initialized = false; Serial.println(F(">> More smoothing")); printSettings(); }
    else if (c == '-') { PROFILES[currentProfile].minCutoff = fminf(PROFILES[currentProfile].minCutoff + 0.25, 10.0); oneEuroX.initialized = false; oneEuroY.initialized = false; Serial.println(F(">> Less smoothing")); printSettings(); }
    else if (c == 'f') { cursorSpeed = fminf(cursorSpeed + 1.0, 15.0); Serial.println(F(">> Faster")); printSettings(); }
    else if (c == 's') { cursorSpeed = fmaxf(cursorSpeed - 1.0, 0.5); Serial.println(F(">> Slower")); printSettings(); }
    else if (c == '[') { PROFILES[currentProfile].deadzone = max(PROFILES[currentProfile].deadzone - 2, 0); Serial.println(F(">> Smaller deadzone")); printSettings(); }
    else if (c == ']') { PROFILES[currentProfile].deadzone = min(PROFILES[currentProfile].deadzone + 2, 50); Serial.println(F(">> Bigger deadzone")); printSettings(); }
    else if (c == '?') { printHelp(); }
  }
}

void printHelp() {
  Serial.println(F("1-5=Profile +=smooth -=less f=fast s=slow [=less dead ]=more dead 0=center r=range ?=help"));
}

void printSettings() {
  Profile p = PROFILES[currentProfile];
  Serial.print(F("[active] ")); Serial.print(p.name);
  Serial.print(F("  cutoff=")); Serial.print(p.minCutoff, 2);
  Serial.print(F("  deadzone=")); Serial.print(p.deadzone);
  Serial.print(F("  speed=")); Serial.println(cursorSpeed, 1);
}

float normalize(int raw, int center, int range) {
  float v = ((float)(raw - center) / (float)range) * 100.0;
  return constrain(v, -100.0, 100.0);
}
float applyDeadzone(float value, int dz) {
  float abv = fabs(value);
  if (abv < (float)dz) return 0.0;
  float sign = (value > 0) ? 1.0 : -1.0;
  return sign * ((abv - dz) / (100.0 - dz)) * 100.0;
}
float median3(float a, float b, float c) {
  if ((a >= b && a <= c) || (a <= b && a >= c)) return a;
  if ((b >= a && b <= c) || (b <= a && b >= c)) return b;
  return c;
}
float oneEuroFilter(OneEuro &state, float x, float dt, float minCutoff, float beta) {
  if (!state.initialized) { state.xPrev = x; state.dxPrev = 0; state.yPrev = x; state.initialized = true; return x; }
  float dx = (x - state.xPrev) / dt;
  float aD = lowpassAlpha(dt, DCUTOFF);
  float dxSmooth = aD * dx + (1.0 - aD) * state.dxPrev;
  float cutoff = minCutoff + beta * fabs(dxSmooth);
  float a = lowpassAlpha(dt, cutoff);
  float y = a * x + (1.0 - a) * state.yPrev;
  state.xPrev = x; state.dxPrev = dxSmooth; state.yPrev = y;
  return y;
}
float lowpassAlpha(float dt, float cutoff) {
  float tau = 1.0 / (2.0 * PI * cutoff);
  return 1.0 / (1.0 + tau / dt);
}
void calibrateRange(unsigned long durationMs) {
  int minX=1023,maxX=0,minY=1023,maxY=0;
  unsigned long start = millis();
  while (millis()-start < durationMs) { int x=analogRead(PIN_X); int y=analogRead(PIN_Y); if(x<minX)minX=x; if(x>maxX)maxX=x; if(y<minY)minY=y; if(y>maxY)maxY=y; delay(5); }
  int halfX=min(centerX-minX, maxX-centerX); int halfY=min(centerY-minY, maxY-centerY);
  if(halfX>50)rangeX=halfX; if(halfY>50)rangeY=halfY;
  oneEuroX.initialized=false; oneEuroY.initialized=false; cursorAccumX=0; cursorAccumY=0;
}
void calibrateCenter(unsigned long durationMs) {
  unsigned long start=millis(); long sumX=0,sumY=0; int count=0;
  while(millis()-start<durationMs){sumX+=analogRead(PIN_X);sumY+=analogRead(PIN_Y);count++;delay(2);}
  if(count>0){centerX=sumX/count;centerY=sumY/count;}
  idleAvgX=(float)centerX; idleAvgY=(float)centerY; isStill=false;
  oneEuroX.initialized=false; oneEuroY.initialized=false;
  for(int i=0;i<3;i++){medianBufX[i]=0;medianBufY[i]=0;}
  cursorAccumX=0; cursorAccumY=0;
}`;

// ============================================================
// PROFILE DATA
// ============================================================
const PROFILES = [
  { name: 'Steady',   minCutoff: 5.00, beta: 0.020, deadzone: 8 },
  { name: 'Mild',     minCutoff: 2.00, beta: 0.015, deadzone: 12 },
  { name: 'Moderate', minCutoff: 1.00, beta: 0.010, deadzone: 16 },
  { name: 'Heavy',    minCutoff: 0.50, beta: 0.007, deadzone: 20 },
  { name: 'Severe',   minCutoff: 0.25, beta: 0.005, deadzone: 26 },
];

const BUTTON_ACTIONS = {
  mouse_left: 'MOUSE_LEFT',
  mouse_right: 'MOUSE_RIGHT',
  mouse_middle: 'MOUSE_MIDDLE',
  key_enter: 'KEY_RETURN',
  key_space: "' '",
  key_esc: 'KEY_ESC'
};

// ============================================================
// APP STATE
// ============================================================
const state = {
  currentProfile: 2,
  cursorSpeed: 4.0,
  sensors: [],
  buttonMappings: { joystick_click: 'mouse_left' },
  nextSensorPin: 4,
  snakeRunning: false,
  snakeScore: 0,
  dirty: false, // unsaved changes
};

let serialManager = null;
let autoSaveTimer = null;

// ============================================================
// SERIAL HANDLING
// ============================================================
function onSerialData(line) {
  // Add to serial monitor
  const output = document.getElementById('serialOutput');
  const div = document.createElement('div');

  // Color code
  if (line.startsWith('>>') || line.startsWith('[active]') || line.startsWith('===')) {
    div.className = 'line-info';
  } else if (line.includes('ERROR') || line.includes('FAIL')) {
    div.className = 'line-error';
  }
  div.textContent = line;
  output.appendChild(div);
  output.scrollTop = output.scrollHeight;

  // Parse telemetry: filtX,filtY,enabled
  const parts = line.split(',');
  if (parts.length === 3 && !isNaN(parts[0])) {
    const x = parseInt(parts[0]);
    const y = parseInt(parts[1]);
    const enabled = parseInt(parts[2]);
    updateJoystickMockup(x, y, enabled);
    if (state.snakeRunning) {
      updateSnakeDirection(x, y);
    }
  }
}

function onSerialConnect() {
  document.getElementById('statusDot').classList.add('connected');
  document.getElementById('statusText').textContent = 'Connected';
  document.getElementById('wiringStatusDot').classList.add('connected');
  document.getElementById('wiringConnectionTitle').textContent = 'Arduino Connected';
  document.getElementById('wiringConnectionDetail').textContent = 'Receiving data at 115200 baud';
  document.getElementById('connectBtn').textContent = 'Disconnect';
  document.getElementById('connectBtn').className = 'btn btn-danger';
  document.getElementById('connectBtn').onclick = () => app.serial.disconnect();
  document.getElementById('wiringConnectBtn').textContent = 'Disconnect';
  document.getElementById('wiringConnectBtn').onclick = () => app.serial.disconnect();
  window.app.toast('Arduino connected!', 'success');
}

function onSerialDisconnect() {
  document.getElementById('statusDot').classList.remove('connected');
  document.getElementById('statusText').textContent = 'Disconnected';
  document.getElementById('wiringStatusDot').classList.remove('connected');
  document.getElementById('wiringConnectionTitle').textContent = 'No Device Connected';
  document.getElementById('wiringConnectionDetail').textContent = 'Click "Connect" to pair your Arduino Leonardo via Web Serial';
  document.getElementById('connectBtn').textContent = 'Connect';
  document.getElementById('connectBtn').className = 'btn btn-success';
  document.getElementById('connectBtn').onclick = () => app.serial.connect();
  document.getElementById('wiringConnectBtn').textContent = 'Connect Arduino';
  document.getElementById('wiringConnectBtn').onclick = () => app.serial.connect();
}

// ============================================================
// JOYSTICK MOCKUP
// ============================================================
function updateJoystickMockup(x, y, enabled) {
  const cursor = document.getElementById('mockupCursor');
  if (!cursor) return;

  // Map -100..100 to pixel offset within 200px circle
  const baseSize = 200;
  const maxOffset = baseSize / 2 - 10;
  const px = (x / 100) * maxOffset;
  const py = (y / 100) * maxOffset;

  cursor.style.left = `${baseSize / 2 + px - 6}px`;
  cursor.style.top = `${baseSize / 2 + py - 6}px`;

  document.getElementById('mockupX').textContent = x;
  document.getElementById('mockupY').textContent = y;
  document.getElementById('mockupEnabled').textContent = enabled ? 'Yes' : 'No';
  document.getElementById('mockupEnabled').style.color = enabled ? 'var(--green)' : 'var(--red)';
}

// ============================================================
// SNAKE GAME
// ============================================================
let snakeGame = null;

function initSnake() {
  const canvas = document.getElementById('snakeCanvas');
  const ctx = canvas.getContext('2d');
  const gridSize = 20;
  const cols = Math.floor(canvas.width / gridSize);
  const rows = Math.floor(canvas.height / gridSize);

  snakeGame = {
    canvas, ctx, gridSize, cols, rows,
    snake: [{ x: Math.floor(cols / 2), y: Math.floor(rows / 2) }],
    food: null,
    direction: { x: 1, y: 0 },
    nextDirection: { x: 1, y: 0 },
    score: 0,
    interval: null,
    mouseX: canvas.width / 2,
    mouseY: canvas.height / 2,
    useMouseControl: true
  };

  spawnFood();
  drawSnake();

  // Mouse control for the snake
  canvas.addEventListener('mousemove', (e) => {
    const rect = canvas.getBoundingClientRect();
    snakeGame.mouseX = (e.clientX - rect.left) * (canvas.width / rect.width);
    snakeGame.mouseY = (e.clientY - rect.top) * (canvas.height / rect.height);
  });

  // Keyboard fallback
  document.addEventListener('keydown', (e) => {
    if (!state.snakeRunning) return;
    switch (e.key) {
      case 'ArrowUp':    snakeGame.nextDirection = { x: 0, y: -1 }; break;
      case 'ArrowDown':  snakeGame.nextDirection = { x: 0, y: 1 }; break;
      case 'ArrowLeft':  snakeGame.nextDirection = { x: -1, y: 0 }; break;
      case 'ArrowRight': snakeGame.nextDirection = { x: 1, y: 0 }; break;
    }
  });
}

function spawnFood() {
  if (!snakeGame) return;
  snakeGame.food = {
    x: Math.floor(Math.random() * snakeGame.cols),
    y: Math.floor(Math.random() * snakeGame.rows)
  };
}

function updateSnakeDirection(joystickX, joystickY) {
  if (!snakeGame || !state.snakeRunning) return;
  // Use joystick telemetry to steer snake
  const threshold = 20;
  if (Math.abs(joystickX) > Math.abs(joystickY)) {
    if (joystickX > threshold) snakeGame.nextDirection = { x: 1, y: 0 };
    else if (joystickX < -threshold) snakeGame.nextDirection = { x: -1, y: 0 };
  } else {
    if (joystickY > threshold) snakeGame.nextDirection = { x: 0, y: 1 };
    else if (joystickY < -threshold) snakeGame.nextDirection = { x: 0, y: -1 };
  }
}

function tickSnake() {
  if (!snakeGame) return;
  const g = snakeGame;

  // Mouse-based direction (if not controlled by joystick serial data)
  if (g.useMouseControl && !serialManager?.connected) {
    const head = g.snake[0];
    const headPx = { x: head.x * g.gridSize + g.gridSize / 2, y: head.y * g.gridSize + g.gridSize / 2 };
    const dx = g.mouseX - headPx.x;
    const dy = g.mouseY - headPx.y;
    if (Math.abs(dx) > Math.abs(dy)) {
      g.nextDirection = { x: dx > 0 ? 1 : -1, y: 0 };
    } else {
      g.nextDirection = { x: 0, y: dy > 0 ? 1 : -1 };
    }
  }

  // Prevent reverse
  if (g.nextDirection.x !== -g.direction.x || g.nextDirection.y !== -g.direction.y) {
    g.direction = { ...g.nextDirection };
  }

  const head = g.snake[0];
  const newHead = { x: head.x + g.direction.x, y: head.y + g.direction.y };

  // Wrap around
  if (newHead.x < 0) newHead.x = g.cols - 1;
  if (newHead.x >= g.cols) newHead.x = 0;
  if (newHead.y < 0) newHead.y = g.rows - 1;
  if (newHead.y >= g.rows) newHead.y = 0;

  // Self collision
  if (g.snake.some(s => s.x === newHead.x && s.y === newHead.y)) {
    state.snakeRunning = false;
    clearInterval(g.interval);
    window.app.toast(`Game Over! Score: ${g.score}`, 'error');
    return;
  }

  g.snake.unshift(newHead);

  // Eat food
  if (g.food && newHead.x === g.food.x && newHead.y === g.food.y) {
    g.score++;
    document.getElementById('snakeScore').textContent = g.score;
    spawnFood();
  } else {
    g.snake.pop();
  }

  drawSnake();
}

function drawSnake() {
  if (!snakeGame) return;
  const { ctx, canvas, gridSize, snake, food, cols, rows } = snakeGame;

  // Background
  ctx.fillStyle = '#08080d';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Grid lines
  ctx.strokeStyle = '#1a1a26';
  ctx.lineWidth = 0.5;
  for (let x = 0; x < cols; x++) {
    ctx.beginPath();
    ctx.moveTo(x * gridSize, 0);
    ctx.lineTo(x * gridSize, canvas.height);
    ctx.stroke();
  }
  for (let y = 0; y < rows; y++) {
    ctx.beginPath();
    ctx.moveTo(0, y * gridSize);
    ctx.lineTo(canvas.width, y * gridSize);
    ctx.stroke();
  }

  // Food
  if (food) {
    ctx.fillStyle = '#ef4444';
    ctx.shadowColor = '#ef4444';
    ctx.shadowBlur = 8;
    ctx.beginPath();
    ctx.arc(food.x * gridSize + gridSize / 2, food.y * gridSize + gridSize / 2, gridSize / 2 - 2, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;
  }

  // Snake
  snake.forEach((seg, i) => {
    const alpha = 1 - (i / snake.length) * 0.6;
    ctx.fillStyle = i === 0 ? '#818cf8' : `rgba(99, 102, 241, ${alpha})`;
    if (i === 0) {
      ctx.shadowColor = '#6366f1';
      ctx.shadowBlur = 10;
    }
    ctx.fillRect(seg.x * gridSize + 1, seg.y * gridSize + 1, gridSize - 2, gridSize - 2);
    ctx.shadowBlur = 0;
  });
}

// ============================================================
// GAMEPAD API (Xbox Adaptive Controller support)
// ============================================================
let gamepadPollInterval = null;

function startGamepadPolling() {
  if (gamepadPollInterval) return;
  gamepadPollInterval = setInterval(pollGamepads, 16); // ~60fps
}

function pollGamepads() {
  const gamepads = navigator.getGamepads();
  let activeCount = 0;

  for (const gp of gamepads) {
    if (!gp) continue;

    // Buttons
    const buttonMap = [
      'A', 'B', 'X', 'Y', 'LB', 'RB', 'LT', 'RT',
      'View', 'MenuBtn', 'LeftStickPress', 'RightStickPress',
      'DUp', 'DDown', 'DLeft', 'DRight', 'Menu'
    ];

    gp.buttons.forEach((btn, i) => {
      const name = buttonMap[i] || `Btn${i}`;
      const el = document.querySelector(`[data-btn="${name}"]`);
      if (el) {
        if (btn.pressed) {
          el.classList.add('active');
          activeCount++;
        } else {
          el.classList.remove('active');
        }
      }
    });

    // Sticks
    if (gp.axes.length >= 2) {
      const lx = gp.axes[0];
      const ly = gp.axes[1];
      const dot = document.getElementById('leftStickDot');
      if (dot) {
        dot.style.transform = `translate(${lx * 18}px, ${ly * 18}px)`;
        if (Math.abs(lx) > 0.1 || Math.abs(ly) > 0.1) activeCount++;
      }

      // Use left stick for snake if connected
      if (state.snakeRunning && snakeGame) {
        const threshold = 0.3;
        if (Math.abs(lx) > Math.abs(ly)) {
          if (lx > threshold) snakeGame.nextDirection = { x: 1, y: 0 };
          else if (lx < -threshold) snakeGame.nextDirection = { x: -1, y: 0 };
        } else {
          if (ly > threshold) snakeGame.nextDirection = { x: 0, y: 1 };
          else if (ly < -threshold) snakeGame.nextDirection = { x: 0, y: -1 };
        }
      }
    }
    if (gp.axes.length >= 4) {
      const rx = gp.axes[2];
      const ry = gp.axes[3];
      const dot = document.getElementById('rightStickDot');
      if (dot) {
        dot.style.transform = `translate(${rx * 18}px, ${ry * 18}px)`;
        if (Math.abs(rx) > 0.1 || Math.abs(ry) > 0.1) activeCount++;
      }
    }
  }

  document.getElementById('inputCount').textContent = `${activeCount} inputs active`;
}

// ============================================================
// APP OBJECT
// ============================================================
const app = {
  serial: {
    async connect() {
      try {
        if (serialManager?.connected) {
          await serialManager.disconnect();
          return;
        }
        serialManager = new SerialManager(onSerialData, onSerialConnect, onSerialDisconnect);
        await serialManager.connect();
      } catch (e) {
        window.app.toast(e.message, 'error');
      }
    },
    async disconnect() {
      if (serialManager) await serialManager.disconnect();
    }
  },

  auth: authModule,

  switchTab(name) {
    document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab === name));
    document.querySelectorAll('.tab-content').forEach(t => t.classList.toggle('active', t.id === `tab-${name}`));
  },

  wiring: {
    editSetup() {
      window.app.toast('Edit your wiring in the Configure tab by adding sensors', 'success');
      app.switchTab('configure');
    }
  },

  configure: {
    setProfile(idx) {
      state.currentProfile = idx;
      const p = PROFILES[idx];
      document.querySelectorAll('.profile-btn').forEach((b, i) => b.classList.toggle('active', i === idx));
      document.getElementById('smoothSlider').value = p.minCutoff;
      document.getElementById('smoothVal').textContent = p.minCutoff.toFixed(2) + ' Hz';
      document.getElementById('deadSlider').value = p.deadzone;
      document.getElementById('deadVal').textContent = p.deadzone;
      // Send to Arduino
      if (serialManager?.connected) {
        serialManager.send(String(idx + 1));
      }
      markDirty();
    },

    updateSmoothing(val) {
      PROFILES[state.currentProfile].minCutoff = parseFloat(val);
      document.getElementById('smoothVal').textContent = parseFloat(val).toFixed(2) + ' Hz';
      markDirty();
    },

    updateSpeed(val) {
      state.cursorSpeed = parseFloat(val);
      document.getElementById('speedVal').textContent = parseFloat(val).toFixed(1);
      markDirty();
    },

    updateDeadzone(val) {
      PROFILES[state.currentProfile].deadzone = parseInt(val);
      document.getElementById('deadVal').textContent = val;
      markDirty();
    },

    remapButton(name, action) {
      state.buttonMappings[name] = action;
      markDirty();
    },

    addSensor(type) {
      const pin = state.nextSensorPin++;
      const sensor = { type, pin: `D${pin}`, id: Date.now() };
      state.sensors.push(sensor);
      renderSensors();
      renderComponents();
      markDirty();
      window.app.toast(`Added ${type.replace('_', ' ')} on pin D${pin}`, 'success');
    },

    removeSensor(id) {
      state.sensors = state.sensors.filter(s => s.id !== id);
      renderSensors();
      renderComponents();
      markDirty();
    },

    calibrateCenter() {
      if (serialManager?.connected) {
        serialManager.send('0');
        window.app.toast('Center calibration started - hold joystick still', 'success');
      } else {
        window.app.toast('Connect Arduino first', 'error');
      }
    },

    calibrateRange() {
      if (serialManager?.connected) {
        serialManager.send('r');
        window.app.toast('Range calibration started - swirl joystick for 3 seconds', 'success');
      } else {
        window.app.toast('Connect Arduino first', 'error');
      }
    },

    compile() {
      if (!serialManager?.connected) {
        window.app.toast('Connect your Arduino first to compile and upload', 'error');
        return;
      }
      window.app.toast('Compile & Upload requires Arduino CLI. Use "View Sketch" to get the code for Arduino IDE.', 'error');
    },

    showSketch() {
      const code = generateSketch();
      document.getElementById('sketchCode').textContent = code;
      document.getElementById('sketchModal').classList.add('open');
    },

    closeSketch() {
      document.getElementById('sketchModal').classList.remove('open');
    },

    copySketch() {
      const code = document.getElementById('sketchCode').textContent;
      navigator.clipboard.writeText(code).then(() => {
        window.app.toast('Sketch copied to clipboard!', 'success');
      });
    }
  },

  test: {
    startSnake() {
      if (!snakeGame) initSnake();
      if (state.snakeRunning) return;
      state.snakeRunning = true;
      snakeGame.score = 0;
      snakeGame.snake = [{ x: Math.floor(snakeGame.cols / 2), y: Math.floor(snakeGame.rows / 2) }];
      snakeGame.direction = { x: 1, y: 0 };
      snakeGame.nextDirection = { x: 1, y: 0 };
      document.getElementById('snakeScore').textContent = '0';
      spawnFood();
      snakeGame.interval = setInterval(tickSnake, 120);
    },

    resetSnake() {
      state.snakeRunning = false;
      if (snakeGame?.interval) clearInterval(snakeGame.interval);
      if (snakeGame) {
        snakeGame.score = 0;
        snakeGame.snake = [{ x: Math.floor(snakeGame.cols / 2), y: Math.floor(snakeGame.rows / 2) }];
        document.getElementById('snakeScore').textContent = '0';
        drawSnake();
      }
    },

    clearSerial() {
      document.getElementById('serialOutput').innerHTML = '<div class="line-info">-- Serial Monitor cleared --</div>';
    },

    sendSerial() {
      const input = document.getElementById('serialInput');
      const cmd = input.value.trim();
      if (!cmd) return;
      if (serialManager?.connected) {
        serialManager.send(cmd);
        const output = document.getElementById('serialOutput');
        const div = document.createElement('div');
        div.style.color = 'var(--yellow)';
        div.textContent = `> ${cmd}`;
        output.appendChild(div);
        output.scrollTop = output.scrollHeight;
      } else {
        window.app.toast('Connect Arduino first', 'error');
      }
      input.value = '';
    }
  },

  toast(message, type = 'success') {
    const el = document.getElementById('toast');
    el.textContent = message;
    el.className = `toast ${type} show`;
    setTimeout(() => el.classList.remove('show'), 3000);
  }
};

// ============================================================
// HELPERS
// ============================================================
function renderSensors() {
  const container = document.getElementById('addedSensors');
  container.innerHTML = state.sensors.map(s => `
    <div class="added-sensor">
      <div class="sensor-info">
        <span class="sensor-type">${s.type.replace('_', ' ')}</span>
        <span class="sensor-pin">Pin ${s.pin}</span>
      </div>
      <button class="remove-sensor" onclick="app.configure.removeSensor(${s.id})">&times;</button>
    </div>
  `).join('');

  // Also add remap entries for added sensors
  const remapGrid = document.getElementById('remapGrid');
  const existingCustom = remapGrid.querySelectorAll('.remap-custom');
  existingCustom.forEach(el => el.remove());

  state.sensors.forEach(s => {
    const div = document.createElement('div');
    div.className = 'remap-item remap-custom';
    div.innerHTML = `
      <span class="remap-label">${s.type.replace('_', ' ')} (${s.pin})</span>
      <select onchange="app.configure.remapButton('${s.id}', this.value)">
        <option value="mouse_left">Left Click</option>
        <option value="mouse_right">Right Click</option>
        <option value="mouse_middle">Middle Click</option>
        <option value="key_enter">Enter</option>
        <option value="key_space">Space</option>
        <option value="key_esc">Escape</option>
      </select>
    `;
    remapGrid.appendChild(div);
  });
}

function renderComponents() {
  const count = 4 + state.sensors.length;
  document.getElementById('componentCount').textContent = `${count} Components`;

  const list = document.getElementById('componentList');
  // Keep base components, add sensor components
  const sensorHtml = state.sensors.map(s => `
    <div class="component-item">
      <span class="pin">${s.pin}</span>
      <div>
        <div class="label">${s.type.replace('_', ' ').replace(/\b\w/g, c => c.toUpperCase())}</div>
        <div class="desc">Digital input, added sensor</div>
      </div>
    </div>
  `).join('');

  // Remove old dynamic components
  list.querySelectorAll('.dynamic-component').forEach(el => el.remove());
  if (sensorHtml) {
    const wrapper = document.createElement('div');
    wrapper.className = 'dynamic-component';
    wrapper.innerHTML = sensorHtml;
    // Unwrap
    while (wrapper.firstChild) {
      const child = wrapper.firstChild;
      child.classList.add('dynamic-component');
      list.appendChild(child);
    }
  }
}

function generateSketch() {
  let code = SKETCH_TEMPLATE;
  code = code.replace('%%PROFILE%%', String(state.currentProfile));
  code = code.replace(/%%SPEED%%/g, state.cursorSpeed.toFixed(1));

  const mainAction = BUTTON_ACTIONS[state.buttonMappings.joystick_click] || 'MOUSE_LEFT';
  code = code.replace(/%%BUTTON_ACTION%%/g, mainAction);

  // Extra pins
  let extraPins = '';
  let extraSetup = '';
  let extraLogic = '';

  state.sensors.forEach(s => {
    const pinNum = parseInt(s.pin.replace('D', ''));
    extraPins += `const int PIN_${s.type.toUpperCase()} = ${pinNum};\n`;
    extraSetup += `  pinMode(PIN_${s.type.toUpperCase()}, INPUT_PULLUP);\n`;
    const action = BUTTON_ACTIONS[state.buttonMappings[s.id] || 'mouse_left'];
    extraLogic += `    // ${s.type} on ${s.pin}\n`;
    extraLogic += `    if (digitalRead(PIN_${s.type.toUpperCase()}) == LOW) Mouse.press(${action});\n`;
    extraLogic += `    else Mouse.release(${action});\n`;
  });

  code = code.replace('%%EXTRA_PINS%%', extraPins);
  code = code.replace('%%EXTRA_SETUP%%', extraSetup);
  code = code.replace('%%EXTRA_BUTTON_LOGIC%%', extraLogic);

  return code;
}

function markDirty() {
  state.dirty = true;
  authModule.hasUnsavedWork = true;

  // Auto-save if signed in
  if (authModule.user) {
    clearTimeout(autoSaveTimer);
    const indicator = document.getElementById('saveIndicator');
    indicator.style.display = 'flex';
    indicator.className = 'save-indicator saving';
    document.getElementById('saveText').textContent = 'Saving...';

    autoSaveTimer = setTimeout(async () => {
      await authModule.saveConfig({
        currentProfile: state.currentProfile,
        cursorSpeed: state.cursorSpeed,
        profiles: PROFILES,
        sensors: state.sensors,
        buttonMappings: state.buttonMappings,
        board: document.getElementById('boardSelect').value
      });
      state.dirty = false;
      authModule.hasUnsavedWork = false;
      indicator.className = 'save-indicator saved';
      document.getElementById('saveText').textContent = 'Saved';
      setTimeout(() => { indicator.style.display = 'none'; }, 2000);
    }, 1500);
  }
}

// ============================================================
// INIT
// ============================================================
function init() {
  window.app = app;

  // Init auth
  authModule.onConfigLoaded = (config) => {
    if (config.currentProfile !== undefined) {
      app.configure.setProfile(config.currentProfile);
    }
    if (config.cursorSpeed !== undefined) {
      state.cursorSpeed = config.cursorSpeed;
      document.getElementById('speedSlider').value = config.cursorSpeed;
      document.getElementById('speedVal').textContent = config.cursorSpeed.toFixed(1);
    }
    if (config.sensors) {
      state.sensors = config.sensors;
      state.nextSensorPin = 4 + config.sensors.length;
      renderSensors();
      renderComponents();
    }
    if (config.buttonMappings) {
      state.buttonMappings = config.buttonMappings;
    }
    if (config.board) {
      document.getElementById('boardSelect').value = config.board;
    }
    window.app.toast('Configuration loaded from your account!', 'success');
  };

  authModule.init((user) => {
    const btn = document.getElementById('authBtn');
    const btnText = document.getElementById('authBtnText');
    if (user) {
      btnText.textContent = user.displayName || user.email || 'Account';
      btn.onclick = () => {
        if (confirm('Sign out?')) authModule.signOutUser();
      };
      const indicator = document.getElementById('saveIndicator');
      indicator.style.display = 'flex';
      indicator.className = 'save-indicator saved';
      document.getElementById('saveText').textContent = 'Auto-save on';
      setTimeout(() => { indicator.style.display = 'none'; }, 3000);
    } else {
      btnText.textContent = 'Sign In';
      btn.onclick = () => app.auth.showModal();
    }
  });

  // Init snake
  initSnake();

  // Start gamepad polling
  startGamepadPolling();
  window.addEventListener('gamepadconnected', () => {
    window.app.toast('Gamepad connected!', 'success');
  });

  // Unsaved work protection
  window.addEventListener('beforeunload', (e) => {
    if (state.dirty && !authModule.user) {
      e.preventDefault();
      e.returnValue = 'You have unsaved work! Sign in to save your configuration.';
    }
  });

  // Set initial profile UI
  app.configure.setProfile(2);
}

init();
